# Wir nutzen Nginx (einen Webserver), um die HTML-Datei bereitzustellen
FROM nginx:alpine

# Kopiere deine index.html in den Standard-Ordner von Nginx
COPY index.html /usr/share/nginx/html/index.html

# Nginx läuft auf Port 80
EXPOSE 80